// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdpwsuxqthseqsfurits.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkcHdzdXhxdGhzZXFzZnVyaXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTI1NDksImV4cCI6MjA2NDk2ODU0OX0.oay0DirPxglaqXfhnibRwERqO4kfcjWV5m7XQvWlxZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);